/*
 * generated by Xtext 2.26.0
 */
package adaptersLang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAdaptersLangScopeProvider extends DelegatingScopeProvider {
}
