/*
 * generated by Xtext 2.27.0
 */
package adaptersLang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AdaptersLangStandaloneSetup extends AdaptersLangStandaloneSetupGenerated {

	public static void doSetup() {
		new AdaptersLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
