/*
 * generated by Xtext 2.27.0
 */
package adaptersLang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AdaptersLangUiModule extends AbstractAdaptersLangUiModule {

	public AdaptersLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
