/*
 * generated by Xtext 2.27.0
 */
package adaptersLang.scoping;

import org.eclipse.xtext.scoping.IScope;

import adapters.Adapter;
import adapters.AdaptersPackage;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class AdaptersLangScopeProvider extends AbstractAdaptersLangScopeProvider {
	/*@Override
	public IScope getScope (EObject context, EReference reference) {
		// scope for rule extensions
		if (context instanceof Adapter && reference == AdaptersPackage.Literals.ADAPTER__RULES) {
			
		}
		// default scope
		return super.getScope(context, reference);
	}
*/
}
