/*
 * generated by Xtext 2.27.0
 */
package adaptersLang.ide;

import adaptersLang.AdaptersLangRuntimeModule;
import adaptersLang.AdaptersLangStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AdaptersLangIdeSetup extends AdaptersLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AdaptersLangRuntimeModule(), new AdaptersLangIdeModule()));
	}
	
}
