/*
 * generated by Xtext 2.26.0
 */
package adaptersLang.parser.antlr;

import adaptersLang.parser.antlr.internal.InternalAdaptersLangParser;
import adaptersLang.services.AdaptersLangGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AdaptersLangParser extends AbstractAntlrParser {

	@Inject
	private AdaptersLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAdaptersLangParser createParser(XtextTokenStream stream) {
		return new InternalAdaptersLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AdapterModel";
	}

	public AdaptersLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AdaptersLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
