/*
 * generated by Xtext 2.26.0
 */
package adaptersLang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AdaptersLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("adaptersLang/parser/antlr/internal/InternalAdaptersLang.tokens");
	}
}
