<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statemachine" nsURI="http://StateMachine.org/PL" nsPrefix="smpl">
  <eAnnotations source="features">
    <details key="file" value="model.xml"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//AbstractState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" ordered="false"
        upperBound="-1" eType="#//AbstractTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="current" lowerBound="1"
        eType="#//State">
      <eAnnotations source="presence">
        <details key="condition" value="Executable"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="presence">
        <details key="condition" value="Timed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractState" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//AbstractState">
    <eAnnotations source="presence">
      <details key="condition" value="Hierarchical"/>
      <details key="constraint" value="oneRegion"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="oneRegion"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="oneRegion" value="self.nested->size()=1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entryAction" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="presence">
        <details key="condition" value="EntryAction"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exitAction" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="presence">
        <details key="condition" value="ExitAction"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doAction" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="presence">
        <details key="condition" value="DoAction"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nested" ordered="false"
        upperBound="-1" eType="#//OrthogonalRegion" containment="true">
      <eAnnotations source="presence">
        <details key="condition" value="Hierarchical"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrthogonalRegion">
    <eAnnotations source="presence">
      <details key="condition" value="Hierarchical"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" ordered="false"
        upperBound="-1" eType="#//AbstractState" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoState" abstract="true" eSuperTypes="#//AbstractState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Initial" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Final" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionNode" eSuperTypes="#//PseudoState">
    <eAnnotations source="presence">
      <details key="condition" value="Condition"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//PseudoState">
    <eAnnotations source="presence">
      <details key="condition" value="ForkJoin"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//PseudoState">
    <eAnnotations source="presence">
      <details key="condition" value="ForkJoin"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="History" eSuperTypes="#//PseudoState">
    <eAnnotations source="presence">
      <details key="condition" value="History"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeepHistory" eSuperTypes="#//History">
    <eAnnotations source="presence">
      <details key="condition" value="DeepHistory"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTransition" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noFinalSource noInitialTarget"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="noFinalSource" value="not src.oclIsKindOf(Final)"/>
      <details key="noInitialTarget" value="not tar.oclIsKindOf(Initial)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//AbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tar" lowerBound="1" eType="#//AbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="true">
      <eAnnotations source="presence">
        <details key="condition" value="Guard"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actions" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="">
      <eAnnotations source="presence">
        <details key="condition" value="Actions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beenProcessed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="presence">
        <details key="condition" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTransition" eSuperTypes="#//AbstractTransition">
    <eAnnotations source="presence">
      <details key="condition" value="Events"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedTransition" eSuperTypes="#//AbstractTransition">
    <eAnnotations source="presence">
      <details key="condition" value="Timed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afterTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImmediateTransition" eSuperTypes="#//AbstractTransition">
    <eAnnotations source="presence">
      <details key="condition" value="Immediate or not Trigger"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
